# Generated by Django 3.1.2 on 2020-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('number_of_fields', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
