# Generated by Django 3.1.2 on 2020-10-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='value_baseline',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='value_stdev',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
