# Generated by Django 3.1.2 on 2020-10-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solardata',
            options={'verbose_name_plural': 'SolarData'},
        ),
        migrations.RemoveField(
            model_name='solardata',
            name='data',
        ),
        migrations.CreateModel(
            name='SolarProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('number_of_fields', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.solardata')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
