# Generated by Django 3.1.2 on 2020-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201028_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarproject',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
