# Generated by Django 3.1.4 on 2020-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solarproject_last_queried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarproject',
            name='last_queried',
            field=models.CharField(max_length=50, verbose_name='last queried'),
        ),
    ]
